<?php
// ==========================================
// STI EXAM TIMER - SYSTEM SETUP WIZARD
// ==========================================

$step = 1;
$error = '';
$success = '';

// SECURITY LOCKOUT: Kung may db.php na, bawal na i-run ang setup wizard para iwas hack.
if (file_exists('db.php')) {
    die("
    <div style='font-family: Arial, sans-serif; text-align: center; padding: 50px; background: #001f3f; color: white; height: 100vh;'>
        <h1 style='color: #FF0B2F;'>⚠️ SYSTEM ALREADY CONFIGURED</h1>
        <p>The system has already been set up and locked for security.</p>
        <p>If you need to re-install, please delete the <b>db.php</b> file first.</p>
        <a href='admin.php' style='display: inline-block; margin-top: 20px; padding: 15px 30px; background: #fDD000; color: #001f3f; text-decoration: none; font-weight: bold; border-radius: 5px;'>GO TO ADMIN PANEL</a>
    </div>
    ");
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_host = $_POST['db_host'] ?? 'localhost';
    $db_user = $_POST['db_user'] ?? '';
    $db_pass = $_POST['db_pass'] ?? '';
    $db_name = $_POST['db_name'] ?? '';
    
    $admin_user = $_POST['admin_user'] ?? 'ADMIN';
    $admin_pass = $_POST['admin_pass'] ?? '';
    $proc_pass  = $_POST['proc_pass'] ?? '';
    
    $campus_name = $_POST['campus_name'] ?? 'STI College';

    try {
        // 1. TEST DATABASE CONNECTION
        $pdo = new PDO("mysql:host=$db_host;dbname=$db_name;charset=utf8mb4", $db_user, $db_pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        ]);

        // 2. CREATE DATABASE TABLES AUTOMATICALLY
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS exam_accounts (
                id INT AUTO_INCREMENT PRIMARY KEY,
                username VARCHAR(50) UNIQUE,
                password_hash VARCHAR(255),
                role VARCHAR(20)
            );
            
            CREATE TABLE IF NOT EXISTS exam_settings (
                setting_key VARCHAR(50) PRIMARY KEY,
                setting_value TEXT
            );

            CREATE TABLE IF NOT EXISTS exam_schedules (
                id INT AUTO_INCREMENT PRIMARY KEY,
                subject VARCHAR(255),
                prog_code VARCHAR(50),
                section_code VARCHAR(50),
                room VARCHAR(50),
                proctor VARCHAR(255),
                start_time INT,
                end_time INT,
                actual_start INT NULL,
                day INT,
                status VARCHAR(20) DEFAULT 'pending'
            );

            CREATE TABLE IF NOT EXISTS exam_logs (
                id INT AUTO_INCREMENT PRIMARY KEY,
                log_message TEXT,
                timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
            );
        ");

        // 3. INSERT OR UPDATE ACCOUNTS
        $hashAdmin = password_hash($admin_pass, PASSWORD_DEFAULT);
        $hashProc  = password_hash($proc_pass, PASSWORD_DEFAULT);

        $stmt = $pdo->prepare("INSERT INTO exam_accounts (username, password_hash, role) VALUES (?, ?, 'ADMIN') ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash)");
        $stmt->execute([$admin_user, $hashAdmin]);

        $stmt = $pdo->prepare("INSERT INTO exam_accounts (username, password_hash, role) VALUES ('PROCTOR', ?, 'PROCTOR') ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash)");
        $stmt->execute([$hashProc]);

        // 4. HANDLE LOGO UPLOAD & DIRECTORIES
        if (!is_dir('uploads')) mkdir('uploads', 0777, true);
        if (!is_dir('uploads/gif')) mkdir('uploads/gif', 0777, true);
        if (!is_dir('uploads/10mins')) mkdir('uploads/10mins', 0777, true);
        if (!is_dir('uploads/chime')) mkdir('uploads/chime', 0777, true);

        $logoPath = 'uploads/logo.webp'; // Default fallback
        if (isset($_FILES['campus_logo']) && $_FILES['campus_logo']['error'] == 0) {
            $ext = pathinfo($_FILES['campus_logo']['name'], PATHINFO_EXTENSION);
            $logoPath = 'uploads/campus_logo.' . $ext;
            move_uploaded_file($_FILES['campus_logo']['tmp_name'], $logoPath);
        }

        // 5. SAVE INITIAL SETTINGS
        $settingsPayload = json_encode([
            'campus_name' => $campus_name,
            'logo' => $logoPath,
            'exam_days' => ["", "", "", "", ""],
            'programs' => []
        ]);
        $stmt = $pdo->prepare("INSERT INTO exam_settings (setting_key, setting_value) VALUES ('system_config', ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)");
        $stmt->execute([$settingsPayload]);

        // 6. GENERATE THE db.php FILE (This locks the setup)
        $dbFileContent = "<?php\n";
        $dbFileContent .= "// 🛑 AUTO-GENERATED BY SETUP WIZARD\n";
        $dbFileContent .= "\$host = '$db_host';\n";
        $dbFileContent .= "\$db = '$db_name';\n";
        $dbFileContent .= "\$user = '$db_user';\n";
        $dbFileContent .= "\$pass = '$db_pass';\n";
        $dbFileContent .= "try {\n";
        $dbFileContent .= "    \$pdo = new PDO(\"mysql:host=\$host;dbname=\$db;charset=utf8mb4\", \$user, \$pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);\n";
        $dbFileContent .= "} catch (PDOException \$e) {\n";
        $dbFileContent .= "    die('Database connection failed. Please check db.php');\n";
        $dbFileContent .= "}\n";
        $dbFileContent .= "?>";

        file_put_contents('db.php', $dbFileContent);

        $step = 2; // Move to Success Screen

    } catch (PDOException $e) {
        $error = "Database Error: " . $e->getMessage();
    } catch (Exception $e) {
        $error = "Error: " . $e->getMessage();
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>System Setup - STI Exam Timer</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700;900&family=Oswald:wght@500;700&display=swap" rel="stylesheet">
    <style>
        :root { --sti-yellow: #fDD000; --sti-blue: #003666; --bg: #f4f7f9; --text-dark: #111111; --border: #cccccc;}
        body { font-family: 'Montserrat', sans-serif; background: var(--bg); margin: 0; padding: 0; display: flex; flex-direction: column; min-height: 100vh; align-items: center; justify-content: center; }
        
        .wizard-container { background: white; padding: 40px; border-radius: 15px; box-shadow: 0 10px 30px rgba(0,54,102,0.1); width: 90%; max-width: 800px; border-top: 8px solid var(--sti-yellow); z-index: 2; margin: 40px 0;}
        .header-title { font-family: 'Oswald'; color: var(--sti-blue); font-size: 35px; margin: 0 0 10px 0; text-transform: uppercase; letter-spacing: 1px; text-align: center;}
        .sub-title { color: #555; text-align: center; margin-bottom: 30px; font-weight: 600;}
        
        .grid-form { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
        .form-group { display: flex; flex-direction: column; margin-bottom: 15px; }
        .full-width { grid-column: 1 / -1; }
        
        label { font-weight: 700; color: var(--sti-blue); font-size: 14px; margin-bottom: 5px; text-transform: uppercase; letter-spacing: 0.5px;}
        input[type="text"], input[type="password"], input[type="file"] { padding: 15px; border: 2px solid var(--border); border-radius: 8px; font-family: 'Montserrat'; font-weight: 600; font-size: 14px; transition: 0.2s;}
        input[type="text"]:focus, input[type="password"]:focus { border-color: var(--sti-blue); outline: none; }
        
        .section-header { font-family: 'Oswald'; color: var(--sti-yellow); background: var(--sti-blue); padding: 10px 15px; border-radius: 5px; margin: 20px 0 15px 0; font-size: 20px; grid-column: 1 / -1; letter-spacing: 1px;}
        
        button.btn-submit { background: var(--sti-yellow); color: var(--sti-blue); font-family: 'Oswald'; font-size: 22px; padding: 15px; border: none; border-radius: 8px; cursor: pointer; font-weight: 700; text-transform: uppercase; letter-spacing: 2px; transition: 0.3s; width: 100%; margin-top: 20px;}
        button.btn-submit:hover { transform: translateY(-3px); box-shadow: 0 5px 15px rgba(253, 208, 0, 0.4); }

        .error-box { background: rgba(255, 11, 47, 0.1); color: #FF0B2F; padding: 15px; border-left: 5px solid #FF0B2F; border-radius: 5px; margin-bottom: 20px; font-weight: 700;}
        
        /* THE DIRECTOR's FOOTER */
        .credit-footer { text-align: center; font-size: 12px; color: #777; line-height: 1.6; max-width: 800px; padding: 20px; margin-bottom: 20px;}
        .credit-footer a { color: var(--sti-blue); font-weight: bold; text-decoration: none; transition: 0.2s;}
        .credit-footer a:hover { color: var(--sti-yellow); text-decoration: underline;}

        .success-box { text-align: center; padding: 40px 0; }
        .success-box h1 { font-family: 'Oswald'; color: var(--green); font-size: 50px; margin-bottom: 10px;}
        .btn-launch { display: inline-block; background: var(--sti-blue); color: var(--sti-yellow); text-decoration: none; padding: 15px 40px; font-family: 'Oswald'; font-size: 24px; border-radius: 50px; font-weight: bold; margin-top: 20px; transition: 0.3s;}
        .btn-launch:hover { background: var(--sti-yellow); color: var(--sti-blue); transform: scale(1.05);}
    </style>
</head>
<body>

    <div class="wizard-container">
        <?php if ($step === 1): ?>
            <h1 class="header-title">System Setup Wizard</h1>
            <p class="sub-title">Configure your environment to deploy the Exam Room Timer System.</p>

            <?php if ($error): ?>
                <div class="error-box"><?php echo $error; ?></div>
            <?php endif; ?>

            <form method="POST" enctype="multipart/form-data">
                <div class="grid-form">
                    
                    <div class="section-header">1. MySQL Database Configuration</div>
                    <div class="form-group">
                        <label>Database Host</label>
                        <input type="text" name="db_host" value="localhost" required>
                    </div>
                    <div class="form-group">
                        <label>Database Name</label>
                        <input type="text" name="db_name" placeholder="e.g. sti_exam_db" required>
                    </div>
                    <div class="form-group">
                        <label>Database Username</label>
                        <input type="text" name="db_user" placeholder="e.g. root" required>
                    </div>
                    <div class="form-group">
                        <label>Database Password</label>
                        <input type="password" name="db_pass" placeholder="Leave blank if none">
                    </div>

                    <div class="section-header">2. Administrator & Proctor Setup</div>
                    <div class="form-group">
                        <label>Admin Username (Web Portal)</label>
                        <input type="text" name="admin_user" value="ADMIN" required>
                    </div>
                    <div class="form-group">
                        <label>Admin Password</label>
                        <input type="text" name="admin_pass" placeholder="Create a strong password" required>
                    </div>
                    <div class="form-group full-width">
                        <label>TV Terminal Password (PROCTOR LOGIN)</label>
                        <input type="text" name="proc_pass" placeholder="Master password to unlock Smart TVs" required>
                    </div>

                    <div class="section-header">3. Campus Customization</div>
                    <div class="form-group">
                        <label>Campus Name</label>
                        <input type="text" name="campus_name" placeholder="e.g. STI College Cubao" required>
                    </div>
                    <div class="form-group">
                        <label>Campus Logo (Optional)</label>
                        <input type="file" name="campus_logo" accept="image/png, image/jpeg, image/webp">
                    </div>

                    <div class="form-group full-width">
                        <button type="submit" class="btn-submit">INITIALIZE SYSTEM CONFIGURATION</button>
                    </div>

                </div>
            </form>

        <?php elseif ($step === 2): ?>
            
            <div class="success-box">
                <h1>🎉 SETUP COMPLETE!</h1>
                <p style="font-size: 18px; color: #555; font-weight: 600;">
                    Database tables generated.<br>
                    Accounts registered.<br>
                    System locked for security.
                </p>
                <a href="admin.php" class="btn-launch">LAUNCH ADMIN PANEL</a>
            </div>

        <?php endif; ?>
    </div>

    <!-- DIRECTOR'S CUT FOOTER -->
    <div class="credit-footer">
        This is a project of <a href="https://www.facebook.com/502StudioSTICubao" target="_blank">Team 5:02 Studio</a> of STI College Cubao spearheaded by Mr. Jan Allen Dela Cruz in collaboration with Mr. Rodolfo Ivan Porwelos Maaño, the MIS Team, the Faculty, the Admins, and the STI College Cubao Marketing Team. Project of 2025, All-Rights Reserved.
    </div>

</body>
</html>